# Generated by Django 5.1.4 on 2025-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Platinum'), (2, 'Gold'), (3, 'Silver'), (4, 'Other'), (5, 'Communication')], default='Other'),
        ),
    ]
